language: node_js

node_js: "stable"

cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: _dist
    on:
      branch: master
